# Generated by Django 5.2.6 on 2025-09-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(help_text='Car', max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('version', models.IntegerField()),
                ('price', models.IntegerField()),
                ('speed', models.IntegerField()),
            ],
        ),
    ]
